# Development-only application-controlled GPU capture. Native SDK headers stay private.
set(_capture_profile "$<AND:$<BOOL:${SPARKLE_RHI_WITH_EXTERNAL_CAPTURE}>,$<OR:$<CONFIG:DebugEditor>,$<CONFIG:DevelopmentEditor>>>")
find_path(SPARKLE_RENDERDOC_CAPTURE_INCLUDE_DIR renderdoc_app.h
    PATHS "$ENV{ProgramFiles}/RenderDoc" DOC "Directory containing the official RenderDoc application header")
find_path(SPARKLE_NSIGHT_CAPTURE_INCLUDE_DIR NGFX_GraphicsCapture_D3D12.h
    PATHS "$ENV{ProgramFiles}/NVIDIA Corporation/Nsight Graphics 2026.3.1/SDKs/NsightGraphicsSDK/0.9.2/include"
    DOC "Directory containing the pinned NGFX 0.9.2 SDK headers")
set(_capture_pix_headers "${FETCHCONTENT_BASE_DIR}/winpixeventruntime-src/Include/WinPixEventRuntime")
foreach(_source IN LISTS _sparkle_native_capture_sources)
    target_sources(SparkleRHIDiagnostics PRIVATE "$<${_capture_profile}:${_source}>")
endforeach()
set(_capture_renderdoc 0)
if(SPARKLE_RENDERDOC_CAPTURE_INCLUDE_DIR)
    set(_capture_renderdoc "${_capture_profile}")
    target_include_directories(SparkleRHIDiagnostics PRIVATE "$<${_capture_profile}:${SPARKLE_RENDERDOC_CAPTURE_INCLUDE_DIR}>")
endif()
target_compile_definitions(SparkleRHIDiagnostics PRIVATE SPARKLE_RHI_WITH_RENDERDOC_CAPTURE=${_capture_renderdoc})
if(TARGET SparkleRHI_D3D12)
    target_link_libraries(SparkleRHI_D3D12 PRIVATE "$<${_capture_profile}:ole32>" "$<${_capture_profile}:oleaut32>" "$<${_capture_profile}:uuid>")
    foreach(_source IN LISTS _sparkle_d3d12_capture_sources)
        target_sources(SparkleRHI_D3D12 PRIVATE "$<${_capture_profile}:${_source}>")
    endforeach()
    set(_capture_pix 0)
    if(EXISTS "${_capture_pix_headers}/pix3.h")
        set(_capture_pix "${_capture_profile}")
        target_include_directories(SparkleRHI_D3D12 PRIVATE "$<${_capture_profile}:${_capture_pix_headers}>")
        target_compile_definitions(SparkleRHI_D3D12 PRIVATE "$<${_capture_profile}:USE_PIX=1>")
    endif()
    set(_capture_nsight 0)
    if(SPARKLE_NSIGHT_CAPTURE_INCLUDE_DIR)
        set(_capture_nsight "${_capture_profile}")
        target_include_directories(SparkleRHI_D3D12 PRIVATE "$<${_capture_profile}:${SPARKLE_NSIGHT_CAPTURE_INCLUDE_DIR}>")
    endif()
    target_compile_definitions(SparkleRHI_D3D12 PRIVATE SPARKLE_RHI_WITH_PIX_CAPTURE=${_capture_pix} SPARKLE_RHI_WITH_NSIGHT_CAPTURE=${_capture_nsight})
endif()

# SDK inline code carries its notices; installed capturer DLLs are never staged.
set(_capture_notices "")
if(EXISTS "${_capture_pix_headers}/../../license.txt")
    list(APPEND _capture_notices "${_capture_pix_headers}/../../license.txt|ExternalCapture-PIX-LICENSE.txt")
endif()
if(SPARKLE_NSIGHT_CAPTURE_INCLUDE_DIR AND EXISTS "${SPARKLE_NSIGHT_CAPTURE_INCLUDE_DIR}/../LICENSE.txt")
    list(APPEND _capture_notices "${SPARKLE_NSIGHT_CAPTURE_INCLUDE_DIR}/../LICENSE.txt|ExternalCapture-NGFX-LICENSE.txt")
endif()
if(SPARKLE_RENDERDOC_CAPTURE_INCLUDE_DIR)
    file(READ "${SPARKLE_RENDERDOC_CAPTURE_INCLUDE_DIR}/renderdoc_app.h" _renderdoc_header)
    string(FIND "${_renderdoc_header}" "*/" _renderdoc_license_end)
    math(EXPR _renderdoc_license_length "${_renderdoc_license_end}+2")
    string(SUBSTRING "${_renderdoc_header}" 0 ${_renderdoc_license_length} _renderdoc_license)
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/ExternalCapture-RenderDoc-LICENSE.txt" "${_renderdoc_license}\n")
    list(APPEND _capture_notices "${CMAKE_CURRENT_BINARY_DIR}/ExternalCapture-RenderDoc-LICENSE.txt|ExternalCapture-RenderDoc-LICENSE.txt")
endif()
set_property(TARGET SparkleRHI PROPERTY SPARKLE_EXTERNAL_CAPTURE_NOTICES "${_capture_notices}")
