#pragma once

#define BRDF_DISTRIBUTION_GGX 1
#define BRDF_DISTRIBUTION_BECKMANN 2
#define BRDF_DISTRIBUTION_BLINN_PHONG 3

#ifndef BRDF_DISTRIBUTION_MODEL
	#define BRDF_DISTRIBUTION_MODEL BRDF_DISTRIBUTION_GGX
#endif

#define BRDF_GEOMETRY_SMITH_GGX 1
#define BRDF_GEOMETRY_SMITH_GGX_CORRELATED 2
#define BRDF_GEOMETRY_SMITH_GGX_CORRELATED_FAST 3
#define BRDF_GEOMETRY_KELEMEN 4
#define BRDF_GEOMETRY_NEUMANN 5

#ifndef BRDF_GEOMETRY_MODEL
	#define BRDF_GEOMETRY_MODEL BRDF_GEOMETRY_SMITH_GGX_CORRELATED
#endif

#define BRDF_FRESNEL_SCHLICK 1
#define BRDF_FRESNEL_SCHLICK_ROUGHNESS 2

#define BRDF_DIFFUSE_LAMBERT 1
#define BRDF_DIFFUSE_BURLEY 2
#define BRDF_DIFFUSE_OREN_NAYAR 3
#define BRDF_DIFFUSE_CHAN 4

#ifndef BRDF_DIFFUSE_MODEL
	#define BRDF_DIFFUSE_MODEL BRDF_DIFFUSE_BURLEY
#endif

#define BRDF_SUBSURFACE_NONE 0
#define BRDF_SUBSURFACE_WRAP 1
#define BRDF_SUBSURFACE_DISNEY 2

#ifndef BRDF_SUBSURFACE_MODEL
	#define BRDF_SUBSURFACE_MODEL BRDF_SUBSURFACE_WRAP
#endif


#define BRDF_SO_NONE 0
#define BRDF_SO_LAGARDE 1
#define BRDF_SO_LAGARDE_APPROX 2

#ifndef BRDF_SO_MODEL
	#define BRDF_SO_MODEL BRDF_SO_NONE
#endif


#define BRDF_MULTIBOUNCE_AO_NONE 0
#define BRDF_MULTIBOUNCE_AO_JIMENEZ 1

#ifndef BRDF_MULTIBOUNCE_AO_MODEL
	#define BRDF_MULTIBOUNCE_AO_MODEL BRDF_MULTIBOUNCE_AO_JIMENEZ
#endif
