file(GLOB_RECURSE SPARKLE_TASKS_PUBLIC_HEADERS CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/Public/*.h)
file(GLOB_RECURSE SPARKLE_TASKS_PRIVATE_SOURCES CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/Private/*.cpp)
file(GLOB_RECURSE SPARKLE_TASKS_PRIVATE_HEADERS CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/Private/*.h)

if(SPARKLE_BUILD_SHARED)
    add_library(SparkleTasks SHARED
        ${SPARKLE_TASKS_PUBLIC_HEADERS}
        ${SPARKLE_TASKS_PRIVATE_SOURCES}
        ${SPARKLE_TASKS_PRIVATE_HEADERS})
    target_compile_definitions(SparkleTasks PRIVATE SPARKLE_TASKS_EXPORTS)
else()
    add_library(SparkleTasks STATIC
        ${SPARKLE_TASKS_PUBLIC_HEADERS}
        ${SPARKLE_TASKS_PRIVATE_SOURCES}
        ${SPARKLE_TASKS_PRIVATE_HEADERS})
    target_compile_definitions(SparkleTasks PUBLIC SPARKLE_STATIC)
endif()

target_include_directories(SparkleTasks
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/Public
        ${CMAKE_CURRENT_SOURCE_DIR}/..
    PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}/Private)
target_compile_features(SparkleTasks PUBLIC cxx_std_20)

source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR}/Public PREFIX "Public" FILES ${SPARKLE_TASKS_PUBLIC_HEADERS})
source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR}/Private PREFIX "Private" FILES ${SPARKLE_TASKS_PRIVATE_SOURCES} ${SPARKLE_TASKS_PRIVATE_HEADERS})
