# Declarative icon collections produce private, profile-specific static assets.
# The service consumes descriptors and never includes this generated catalog.
file(GLOB_RECURSE _icon_manifests CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/Assets/Icons/Icons.json")
set(_icon_catalog "#pragma once\n#include <array>\n#include \"Editor/Public/Icons/EditorIconAsset.h\"\nnamespace EditorIconAssets {\n")
foreach(_icon_configuration IN LISTS CMAKE_CONFIGURATION_TYPES)
    set(_icon_catalog_${_icon_configuration} "${_icon_catalog}")
endforeach()
set(_icon_names "")
foreach(_icon_manifest IN LISTS _icon_manifests)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_icon_manifest}")
    file(READ "${_icon_manifest}" _icon_manifest_json)
    string(JSON _icon_namespace GET "${_icon_manifest_json}" namespace)
    if(NOT _icon_namespace MATCHES "^[A-Z][A-Za-z0-9]*$")
        message(FATAL_ERROR "Invalid icon collection namespace: ${_icon_manifest}")
    endif()
    string(JSON _icon_profile_count LENGTH "${_icon_manifest_json}" profiles)
    if(_icon_profile_count LESS 1)
        message(FATAL_ERROR "Icon collection needs explicit profiles: ${_icon_manifest}")
    endif()
    set(_icon_profiles "")
    math(EXPR _icon_profile_last "${_icon_profile_count} - 1")
    foreach(_icon_index RANGE ${_icon_profile_last})
        string(JSON _icon_profile GET "${_icon_manifest_json}" profiles ${_icon_index})
        if(NOT _icon_profile IN_LIST CMAKE_CONFIGURATION_TYPES OR _icon_profile IN_LIST _icon_profiles)
            message(FATAL_ERROR "Unknown or duplicate icon profile ${_icon_profile}: ${_icon_manifest}")
        endif()
        list(APPEND _icon_profiles "${_icon_profile}")
    endforeach()
    set(_icon_collection "namespace ${_icon_namespace} {\n")
    get_filename_component(_icon_collection_dir "${_icon_manifest}" DIRECTORY)
    string(JSON _icon_count LENGTH "${_icon_manifest_json}" icons)
    if(_icon_count LESS 1)
        message(FATAL_ERROR "Empty icon collection: ${_icon_manifest}")
    endif()
    math(EXPR _icon_last "${_icon_count} - 1")
    foreach(_icon_index RANGE ${_icon_last})
        string(JSON _icon_name GET "${_icon_manifest_json}" icons ${_icon_index} name)
        string(JSON _icon_extent GET "${_icon_manifest_json}" icons ${_icon_index} extent)
        string(JSON _icon_relative_file GET "${_icon_manifest_json}" icons ${_icon_index} file)
        set(_icon_identity "${_icon_namespace}.${_icon_name}")
        if(NOT _icon_name MATCHES "^[A-Z][A-Za-z0-9]*$" OR _icon_identity IN_LIST _icon_names)
            message(FATAL_ERROR "Invalid or duplicate icon name ${_icon_identity}: ${_icon_manifest}")
        endif()
        list(APPEND _icon_names "${_icon_identity}")
        if(NOT _icon_extent MATCHES "^[1-9][0-9]*$" OR _icon_extent GREATER 512)
            message(FATAL_ERROR "Icon extent must be an integer in [1,512]: ${_icon_identity}")
        endif()
        if(IS_ABSOLUTE "${_icon_relative_file}" OR NOT _icon_relative_file MATCHES "\\.rgba$")
            message(FATAL_ERROR "Icon needs a collection-relative RGBA file: ${_icon_identity}")
        endif()
        file(REAL_PATH "${_icon_collection_dir}/${_icon_relative_file}" _icon_file)
        cmake_path(IS_PREFIX _icon_collection_dir "${_icon_file}" NORMALIZE _icon_inside_collection)
        if(NOT _icon_inside_collection OR NOT EXISTS "${_icon_file}")
            message(FATAL_ERROR "Missing or out-of-collection icon file: ${_icon_identity}")
        endif()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_icon_file}")
        math(EXPR _icon_expected_bytes "${_icon_extent} * ${_icon_extent} * 4")
        file(SIZE "${_icon_file}" _icon_bytes)
        if(NOT _icon_bytes EQUAL _icon_expected_bytes)
            message(FATAL_ERROR "Icon RGBA byte count does not match extent: ${_icon_identity}")
        endif()
        file(READ "${_icon_file}" _icon_hex HEX)
        string(REGEX REPLACE "(..)" "0x\\1," _icon_values "${_icon_hex}")
        string(APPEND _icon_collection "inline constexpr std::array<std::uint8_t, ${_icon_bytes}> ${_icon_name}Pixels = {${_icon_values}};\ninline constexpr EditorIconAsset ${_icon_name}{${_icon_extent}, ${_icon_name}Pixels};\n")
    endforeach()
    string(APPEND _icon_collection "}\n")
    foreach(_icon_profile IN LISTS _icon_profiles)
        string(APPEND _icon_catalog_${_icon_profile} "${_icon_collection}")
    endforeach()
endforeach()
foreach(_icon_configuration IN LISTS CMAKE_CONFIGURATION_TYPES)
    string(APPEND _icon_catalog_${_icon_configuration} "}\n")
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/Icons/${_icon_configuration}")
    file(CONFIGURE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/Icons/${_icon_configuration}/EditorIconAssets.h" CONTENT "${_icon_catalog_${_icon_configuration}}" @ONLY)
endforeach()
target_include_directories(SparkleEditor PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/Icons/$<CONFIG>")
