cmake_path(ABSOLUTE_PATH SPARKLE_PACK_FILES_MANIFEST NORMALIZE OUTPUT_VARIABLE _files_manifest)
cmake_path(IS_PREFIX _project_root "${_files_manifest}" NORMALIZE _manifest_is_project_owned)
if(NOT _manifest_is_project_owned OR NOT EXISTS "${_files_manifest}")
    message(FATAL_ERROR "Asset pack file manifest is unavailable inside the project: ${_files_manifest}")
endif()
file(REAL_PATH "${_files_manifest}" _files_manifest_real)
cmake_path(IS_PREFIX _project_root_real "${_files_manifest_real}" NORMALIZE _manifest_real_is_project_owned)
if(NOT _manifest_real_is_project_owned)
    message(FATAL_ERROR "Asset pack file manifest resolves outside the project: ${_files_manifest_real}")
endif()

file(STRINGS "${_files_manifest}" _source_files)
if(NOT _source_files)
    message(FATAL_ERROR "Asset pack file manifest is empty: ${_files_manifest}")
endif()
file(REMOVE_RECURSE "${_staging_root}")
file(MAKE_DIRECTORY "${_staging_root}/${SPARKLE_PACK_ROOT_RELATIVE}")
set(_seen_source_files)
foreach(_source_file IN LISTS _source_files)
    string(REPLACE "|" ";" _fields "${_source_file}")
    list(LENGTH _fields _field_count)
    if(NOT _field_count EQUAL 3)
        message(FATAL_ERROR "Asset pack file manifest entry must be name|bytes|sha256: ${_source_file}")
    endif()
    list(GET _fields 0 _file_name)
    list(GET _fields 1 _file_bytes)
    list(GET _fields 2 _file_sha256)
    if(NOT _file_name MATCHES "^[A-Za-z0-9][A-Za-z0-9_.-]*$" OR _file_name MATCHES "\\.\\."
       OR _file_name IN_LIST _seen_source_files)
        message(FATAL_ERROR "Asset pack file manifest has an unsafe or duplicate name: ${_file_name}")
    endif()
    if(NOT _file_bytes MATCHES "^[0-9]+$" OR _file_bytes EQUAL 0)
        message(FATAL_ERROR "Asset pack file manifest has an invalid byte count: ${_source_file}")
    endif()
    string(LENGTH "${_file_sha256}" _file_sha256_length)
    if(NOT _file_sha256_length EQUAL 64 OR NOT _file_sha256 MATCHES "^[0-9A-Fa-f]+$")
        message(FATAL_ERROR "Asset pack file manifest has an invalid SHA-256: ${_source_file}")
    endif()
    list(APPEND _seen_source_files "${_file_name}")
    set(_staged_file "${_staging_root}/${SPARKLE_PACK_ROOT_RELATIVE}/${_file_name}")
    message(STATUS "Downloading ${SPARKLE_PACK_ID}/${_file_name} (${_file_bytes} bytes).")
    file(DOWNLOAD "${SPARKLE_PACK_URL}${_file_name}" "${_staged_file}"
        SHOW_PROGRESS TLS_VERIFY ON INACTIVITY_TIMEOUT 180 TIMEOUT 21600 STATUS _download_status)
    list(GET _download_status 0 _download_code)
    list(GET _download_status 1 _download_message)
    if(NOT _download_code EQUAL 0)
        message(FATAL_ERROR "Failed to download ${SPARKLE_PACK_ID}/${_file_name}: ${_download_message}")
    endif()
    file(SIZE "${_staged_file}" _downloaded_bytes)
    file(SHA256 "${_staged_file}" _downloaded_sha256)
    string(TOLOWER "${_file_sha256}" _file_sha256)
    string(TOLOWER "${_downloaded_sha256}" _downloaded_sha256)
    if(NOT _downloaded_bytes EQUAL _file_bytes OR NOT _downloaded_sha256 STREQUAL _file_sha256)
        message(FATAL_ERROR "Downloaded ${SPARKLE_PACK_ID}/${_file_name} fails the pinned size or SHA-256 check.")
    endif()
endforeach()
file(SHA256 "${_files_manifest}" _expected_sha256)
set(_payload_hash_label "SourceFilesSha256")
