if(NOT DEFINED GEOMETRY_INSTANCING_SOURCE_DIR)
    set(GEOMETRY_INSTANCING_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../..")
endif()

get_filename_component(
    GEOMETRY_INSTANCING_SOURCE_DIR
    "${GEOMETRY_INSTANCING_SOURCE_DIR}"
    ABSOLUTE
    BASE_DIR "${CMAKE_CURRENT_LIST_DIR}/../.."
)

cmake_path(NORMAL_PATH GEOMETRY_INSTANCING_SOURCE_DIR)

set_property(GLOBAL PROPERTY SPARKLE_GEOMETRY_INSTANCING_VIOLATIONS "")

function(append_geometry_instancing_violation message_text)
    set_property(GLOBAL APPEND PROPERTY SPARKLE_GEOMETRY_INSTANCING_VIOLATIONS "${message_text}")
endfunction()

function(read_required_geometry_instancing_file file_path out_text)
    if(NOT EXISTS "${file_path}")
        append_geometry_instancing_violation("missing required file: ${file_path}")
        set(${out_text} "" PARENT_SCOPE)
        return()
    endif()

    file(READ "${file_path}" file_text)
    set(${out_text} "${file_text}" PARENT_SCOPE)
endfunction()

function(require_geometry_instancing_text file_path text token description)
    string(FIND "${text}" "${token}" match_index)
    if(match_index EQUAL -1)
        cmake_path(RELATIVE_PATH file_path BASE_DIRECTORY "${GEOMETRY_INSTANCING_SOURCE_DIR}" OUTPUT_VARIABLE relative_path)
        append_geometry_instancing_violation("${relative_path}: missing '${token}': ${description}")
    endif()
endfunction()

function(forbid_geometry_instancing_text file_path text token description)
    string(FIND "${text}" "${token}" match_index)
    if(NOT match_index EQUAL -1)
        cmake_path(RELATIVE_PATH file_path BASE_DIRECTORY "${GEOMETRY_INSTANCING_SOURCE_DIR}" OUTPUT_VARIABLE relative_path)
        append_geometry_instancing_violation("${relative_path}: found forbidden '${token}': ${description}")
    endif()
endfunction()

set(source_import_result_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Tools/Import/SourceImportAdapters/Public/SourceImportResult.h")
read_required_geometry_instancing_file("${source_import_result_path}" source_import_result_text)
if(source_import_result_text)
    require_geometry_instancing_text("${source_import_result_path}" "${source_import_result_text}" "ImportedMeshInstanceGroupKind" "source import must preserve importer-neutral instance group kinds")
    require_geometry_instancing_text("${source_import_result_path}" "${source_import_result_text}" "std::vector<ImportedMeshInstanceGroup> meshInstanceGroups" "source import must carry imported instance groups")
endif()

set(source_import_diagnostics_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Tools/Import/SourceImportAdapters/Public/SourceImportDiagnostics.h")
read_required_geometry_instancing_file("${source_import_diagnostics_path}" source_import_diagnostics_text)
if(source_import_diagnostics_text)
    require_geometry_instancing_text("${source_import_diagnostics_path}" "${source_import_diagnostics_text}" "SourceGeometryInstancingDiagnostics" "import diagnostics must expose geometry-instancing counters")
    require_geometry_instancing_text("${source_import_diagnostics_path}" "${source_import_diagnostics_text}" "authoredInstanceGroupCount" "import diagnostics must distinguish authored instance groups")
endif()

set(cooked_scene_manifest_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/GameFramework/Public/Assets/Cooked/CookedSceneManifest.h")
read_required_geometry_instancing_file("${cooked_scene_manifest_path}" cooked_scene_manifest_text)
if(cooked_scene_manifest_text)
    require_geometry_instancing_text("${cooked_scene_manifest_path}" "${cooked_scene_manifest_text}" "CookedSceneInstanceGroupRecord" "cooked scene manifests must preserve instance groups")
    require_geometry_instancing_text("${cooked_scene_manifest_path}" "${cooked_scene_manifest_text}" "kCookedSceneManifestVersion" "manifest versioning must stay explicit for recook-required failures")
endif()

set(scene_manifest_loader_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/GameFramework/Private/Assets/Loaders/SceneManifestLoader.cpp")
read_required_geometry_instancing_file("${scene_manifest_loader_path}" scene_manifest_loader_text)
if(scene_manifest_loader_text)
    require_geometry_instancing_text("${scene_manifest_loader_path}" "${scene_manifest_loader_text}" "Recook the scene asset" "old or incompatible cooked scene manifests must fail with a recook message")
    require_geometry_instancing_text("${scene_manifest_loader_path}" "${scene_manifest_loader_text}" "CookedSceneInstanceGroupKind::AuthoredInstanceGroup" "manifest loading must validate supported instance group kinds")
endif()

set(mesh_snapshot_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/GameFramework/Public/Scene/Meshes/MeshSnapshot.h")
read_required_geometry_instancing_file("${mesh_snapshot_path}" mesh_snapshot_text)
if(mesh_snapshot_text)
    require_geometry_instancing_text("${mesh_snapshot_path}" "${mesh_snapshot_text}" "MeshInstanceGroupSnapshot" "runtime snapshots must expose instance group records to Renderer")
    require_geometry_instancing_text("${mesh_snapshot_path}" "${mesh_snapshot_text}" "std::vector<MeshInstanceGroupSnapshot> meshInstanceGroups" "runtime snapshots must carry mesh instance groups")
endif()

set(render_scene_data_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Renderer/Private/SceneData/RenderSceneData.h")
read_required_geometry_instancing_file("${render_scene_data_path}" render_scene_data_text)
if(render_scene_data_text)
    require_geometry_instancing_text("${render_scene_data_path}" "${render_scene_data_text}" "std::vector<MeshDraw> meshInstances" "renderer scene data must carry shader instance records")
    require_geometry_instancing_text("${render_scene_data_path}" "${render_scene_data_text}" "std::vector<MeshInstanceBatch> meshInstanceBatches" "renderer scene data must carry instanced draw batches")
    forbid_geometry_instancing_text("${render_scene_data_path}" "${render_scene_data_text}" "meshDraws" "legacy per-object draw lists must not return to RenderSceneData")
endif()

set(mesh_batch_builder_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Renderer/Private/SceneData/Builders/MeshInstanceBatchBuilder.cpp")
read_required_geometry_instancing_file("${mesh_batch_builder_path}" mesh_batch_builder_text)
if(mesh_batch_builder_text)
    require_geometry_instancing_text("${mesh_batch_builder_path}" "${mesh_batch_builder_text}" "CanShareBatch" "renderer batch-key construction must stay explicit")
    require_geometry_instancing_text("${mesh_batch_builder_path}" "${mesh_batch_builder_text}" "MeshInstanceBatchSource::SingleInstance" "single-instance draws must still flow through the batch path")
    require_geometry_instancing_text("${mesh_batch_builder_path}" "${mesh_batch_builder_text}" "RejectedInvalidInstanceGroupCount" "invalid group references must be counted by reason")
endif()

set(gbuffer_pass_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Renderer/Private/Passes/GBufferPass.cpp")
read_required_geometry_instancing_file("${gbuffer_pass_path}" gbuffer_pass_text)
if(gbuffer_pass_text)
    require_geometry_instancing_text("${gbuffer_pass_path}" "${gbuffer_pass_text}" "frame.meshInstances.IsValid()" "GBuffer must fail closed when the frame instance buffer is unavailable")
    require_geometry_instancing_text("${gbuffer_pass_path}" "${gbuffer_pass_text}" "DrawIndexedInstanced" "GBuffer must submit instanced draws")
    require_geometry_instancing_text("${gbuffer_pass_path}" "${gbuffer_pass_text}" "references instance range" "GBuffer must validate batch instance ranges before drawing")
endif()

set(gbuffer_shader_metadata_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/RHI/Private/Shaders/GBufferShaders.cpp")
read_required_geometry_instancing_file("${gbuffer_shader_metadata_path}" gbuffer_shader_metadata_text)
if(gbuffer_shader_metadata_text)
    require_geometry_instancing_text("${gbuffer_shader_metadata_path}" "${gbuffer_shader_metadata_text}" "SHADER_PARAMETER_CBUFFER_NAMED(PerFrame" "GBuffer pixel shader metadata must expose viewmode constants")
    require_geometry_instancing_text("${gbuffer_shader_metadata_path}" "${gbuffer_shader_metadata_text}" "SHADER_PARAMETER_RDG_BUFFER_SRV(MeshInstanceData, MeshInstances)" "GBuffer shader metadata must reflect the instance structured buffer")
    require_geometry_instancing_text("${gbuffer_shader_metadata_path}" "${gbuffer_shader_metadata_text}" "MeshInstanceDrawConstantBufferData" "GBuffer shader metadata must reflect first-instance draw constants")
endif()

set(gbuffer_vs_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Assets/Shaders/Passes/Deferred/GBufferVS.hlsl")
read_required_geometry_instancing_file("${gbuffer_vs_path}" gbuffer_vs_text)
if(gbuffer_vs_text)
    require_geometry_instancing_text("${gbuffer_vs_path}" "${gbuffer_vs_text}" "FirstInstance + Input.InstanceId" "GBuffer vertex shader must resolve the raw instance id from first-instance offset plus SV_InstanceID")
    require_geometry_instancing_text("${gbuffer_vs_path}" "${gbuffer_vs_text}" "Output.InstanceId = instanceId" "GBuffer vertex shader must export the raw instance id to the pixel shader")
    require_geometry_instancing_text("${gbuffer_vs_path}" "${gbuffer_vs_text}" "Output.Color = Input.Color" "GBuffer vertex shader must keep vertex color separate from instance id visualization")
endif()

set(instance_view_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Assets/Shaders/Debug/InstanceView.hlsli")
read_required_geometry_instancing_file("${instance_view_path}" instance_view_text)
if(instance_view_text)
    require_geometry_instancing_text("${instance_view_path}" "${instance_view_text}" "HashInstanceId" "instance view color hashing must live in a shared debug shader utility")
    require_geometry_instancing_text("${instance_view_path}" "${instance_view_text}" "MakeInstanceColor" "instance view color generation must live in a shared debug shader utility")
    require_geometry_instancing_text("${instance_view_path}" "${instance_view_text}" "ApplyInstanceGroupVisualization" "instance view GBuffer visualization must live in a shared debug shader utility")
endif()

set(gbuffer_ps_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Assets/Shaders/Passes/Deferred/GBufferPS.hlsl")
read_required_geometry_instancing_file("${gbuffer_ps_path}" gbuffer_ps_text)
if(gbuffer_ps_text)
    require_geometry_instancing_text("${gbuffer_ps_path}" "${gbuffer_ps_text}" "Debug/InstanceView.hlsli" "GBuffer pixel shader must consume shared instance view utilities instead of owning visualization logic")
    require_geometry_instancing_text("${gbuffer_ps_path}" "${gbuffer_ps_text}" "InstanceView::ApplyInstanceGroupVisualization" "GBuffer pixel shader must apply instance group visualization through the shared utility")
    require_geometry_instancing_text("${gbuffer_ps_path}" "${gbuffer_ps_text}" "Input.InstanceId" "GBuffer pixel shader must receive the raw exported instance id separately from vertex color")
endif()

set(vertex_output_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Assets/Shaders/Geometry/VertexOutput.hlsli")
read_required_geometry_instancing_file("${vertex_output_path}" vertex_output_text)
if(vertex_output_text)
    require_geometry_instancing_text("${vertex_output_path}" "${vertex_output_text}" "nointerpolation uint InstanceId" "vertex output must carry the raw instance id without interpolation")
endif()

set(pixel_input_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Assets/Shaders/Geometry/PixelInput.hlsli")
read_required_geometry_instancing_file("${pixel_input_path}" pixel_input_text)
if(pixel_input_text)
    require_geometry_instancing_text("${pixel_input_path}" "${pixel_input_text}" "nointerpolation uint InstanceId" "pixel input must receive the raw instance id separately from vertex color")
endif()

set(visualize_buffers_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Assets/Shaders/Passes/Deferred/VisualizeBuffers.hlsl")
read_required_geometry_instancing_file("${visualize_buffers_path}" visualize_buffers_text)
if(visualize_buffers_text)
    require_geometry_instancing_text("${visualize_buffers_path}" "${visualize_buffers_text}" "ViewMode::InstanceGroups" "visualize pass must display instance group colors after lighting")
endif()

set(render_view_mode_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Renderer/Public/Debug/RenderViewMode.h")
read_required_geometry_instancing_file("${render_view_mode_path}" render_view_mode_text)
if(render_view_mode_text)
    require_geometry_instancing_text("${render_view_mode_path}" "${render_view_mode_text}" "InstanceGroups" "renderer viewmode enum must expose the instance group viewmode")
endif()

set(render_view_mode_constants_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Assets/Shaders/Debug/RenderViewModeConstants.hlsli")
read_required_geometry_instancing_file("${render_view_mode_constants_path}" render_view_mode_constants_text)
if(render_view_mode_constants_text)
    require_geometry_instancing_text("${render_view_mode_constants_path}" "${render_view_mode_constants_text}" "InstanceGroups" "HLSL viewmode constants must stay in sync with the renderer enum")
endif()

set(viewport_top_panel_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Editor/Private/Panels/ViewportTopPanel.cpp")
read_required_geometry_instancing_file("${viewport_top_panel_path}" viewport_top_panel_text)
if(viewport_top_panel_text)
    require_geometry_instancing_text("${viewport_top_panel_path}" "${viewport_top_panel_text}" "RenderViewMode::InstanceGroups" "editor viewport viewmode picker must expose the opt-in instance group viewmode")
    require_geometry_instancing_text("${viewport_top_panel_path}" "${viewport_top_panel_text}" "Instance Groups" "editor viewport viewmode picker must label the instance group viewmode")
endif()

set(vertex_input_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Assets/Shaders/Geometry/VertexInput.hlsli")
read_required_geometry_instancing_file("${vertex_input_path}" vertex_input_text)
if(vertex_input_text)
    require_geometry_instancing_text("${vertex_input_path}" "${vertex_input_text}" "SV_InstanceID" "GBuffer vertex input must expose the draw instance id without changing mesh vertex layouts")
endif()

set(mesh_diagnostics_path "${GEOMETRY_INSTANCING_SOURCE_DIR}/Engine/Renderer/Public/Meshes/MeshDiagnostics.h")
read_required_geometry_instancing_file("${mesh_diagnostics_path}" mesh_diagnostics_text)
if(mesh_diagnostics_text)
    require_geometry_instancing_text("${mesh_diagnostics_path}" "${mesh_diagnostics_text}" "RuntimeAuthoredGroupCount" "editor diagnostics must distinguish authored runtime groups")
    require_geometry_instancing_text("${mesh_diagnostics_path}" "${mesh_diagnostics_text}" "RejectedInvalidInstanceGroupCount" "editor diagnostics must expose rejected candidates by invalid group reason")
    require_geometry_instancing_text("${mesh_diagnostics_path}" "${mesh_diagnostics_text}" "MaxInstancesPerBatch" "editor diagnostics must expose instances-per-batch density")
endif()

get_property(GEOMETRY_INSTANCING_VIOLATIONS GLOBAL PROPERTY SPARKLE_GEOMETRY_INSTANCING_VIOLATIONS)
if(GEOMETRY_INSTANCING_VIOLATIONS)
    list(JOIN GEOMETRY_INSTANCING_VIOLATIONS "\n" GEOMETRY_INSTANCING_VIOLATIONS)
    string(PREPEND GEOMETRY_INSTANCING_VIOLATIONS
        "Geometry instancing readiness validation failed. Import, cook, runtime, renderer batching, GBuffer shader reflection, and editor diagnostics must stay wired as one backend-neutral data path.\n")
    message(FATAL_ERROR "${GEOMETRY_INSTANCING_VIOLATIONS}")
endif()

message(STATUS "Geometry instancing readiness check passed for source import, cooked manifest, runtime snapshot, renderer batches, GBuffer shader binding, and editor diagnostics.")
